### ISSUE TITLE
The Settings Plugin makes even worse assumptions on the project name than the Project Plugin..

### ISSUE THREAD

**Issue by TheGoesen** [gradlex-org/java-module-dependencies#132] opened 2024-10-03 16:10 UTC
So from playing around with the settings Plugin I found the ApplyPluginsAction..
```
       @Override
        public void execute(Project project) {
            if (project.getName().equals(artifact)) {
```

Ok so lets try to quickly state how many problems I see in those lines..

1. A new Action is created for every includeModule, and gets a callback for every project, so this scales with O(n^2)
2. project.getName() instead of getPath is used, so once again things become spicy if one has multiple projects using the same name
3.  the project name is compared to the "artifact". But the artifact property is freely configureable and doesnt need to relate to the projectname at all?

**Comment by jjohannes** [comment] 2024-10-10 14:50
Thanks for all the feedback. But I would appreciate, if you can:
- Report one issue for each bug/enhancement
- Provide a reproducer or concrete specification of what you would like to see / have changed and what the use case for that is


If there is something to do, we should split up this issue. I'll comment on the things from the description below and then close this issue. Please open a new separate issue if you would like to follow up on any of these.

----


> A new Action is created for every includeModule, and gets a callback for every project, so this scales with O(n^2)

Do you see this having a negative performance impact on a real project? How large does the project needs to be so that this is a practical problem? Maybe you can provide a build scan showing the issue.
In any case, I don't know about another way to implement this. But if there is, please share a suggestion.

> - project.getName() instead of getPath is used, so once again things become spicy if one has multiple projects using the same name
> - the project name is compared to the "artifact". But the artifact property is freely configureable and doesnt need to relate to the projectname at all?

This is following best practices. This plugin is opinionated to a certain degree. It could never be a Gradle core feature that supports all theoretical edge cases.

The project name is the **identity** via which the project is addressed and that will be used when published. The term **artifact** here refers to that - the artifact in a Maven coordinate **group:artifact:version**.
In theory, you can have multiple modules with the same **artifact** but different  **group**. But that's quite bad practice, because the artifact name is used (without group) to name the Jar files and then you can have name clashes. For example, if you copy all Jar files into one folder.

I am open to provide some additional configuration options for users that have the need to do this differently. If you have such a use case, please open a separate issue with a reproducer.

**Closed** 2024-10-10 14:50 UTC
Labels: wontfix
